kind: Pod
apiVersion: v1
metadata:
  name: auth0-extract-automation-cronjob-mms87x87u-hq84l
  generateName: auth0-extract-automation-cronjob-mms87x87u-
  namespace: auth0-snowflake-dev
  uid: ec03e6df-5666-467e-a068-3112640df15c
  resourceVersion: '1721154670'
  generation: 1
  creationTimestamp: '2026-07-31T00:53:21Z'
  labels:
    batch.kubernetes.io/controller-uid: 4e19f71e-9a7d-48f7-b530-33c93728e3ac
    batch.kubernetes.io/job-name: auth0-extract-automation-cronjob-mms87x87u
    controller-uid: 4e19f71e-9a7d-48f7-b530-33c93728e3ac
    job-name: auth0-extract-automation-cronjob-mms87x87u
  ownerReferences:
    - apiVersion: batch/v1
      kind: Job
      name: auth0-extract-automation-cronjob-mms87x87u
      uid: 4e19f71e-9a7d-48f7-b530-33c93728e3ac
      controller: true
      blockOwnerDeletion: true
  managedFields:
    - manager: kube-controller-manager
      operation: Update
      apiVersion: v1
      time: '2026-07-31T00:53:21Z'
      fieldsType: FieldsV1
      fieldsV1:
        f:metadata:
          f:generateName: {}
          f:labels:
            .: {}
            f:batch.kubernetes.io/controller-uid: {}
            f:batch.kubernetes.io/job-name: {}
            f:controller-uid: {}
            f:job-name: {}
          f:ownerReferences:
            .: {}
            k:{"uid":"4e19f71e-9a7d-48f7-b530-33c93728e3ac"}: {}
        f:spec:
          f:containers:
            k:{"name":"auth0-extract-automation-cronjob"}:
              .: {}
              f:args: {}
              f:env:
                .: {}
                k:{"name":"akv-secrets"}:
                  .: {}
                  f:name: {}
                  f:value: {}
              f:image: {}
              f:imagePullPolicy: {}
              f:name: {}
              f:resources: {}
              f:terminationMessagePath: {}
              f:terminationMessagePolicy: {}
          f:dnsPolicy: {}
          f:enableServiceLinks: {}
          f:imagePullSecrets:
            .: {}
            k:{"name":"registrykey"}: {}
          f:restartPolicy: {}
          f:schedulerName: {}
          f:securityContext: {}
          f:terminationGracePeriodSeconds: {}
    - manager: kubelet
      operation: Update
      apiVersion: v1
      time: '2026-07-31T00:53:25Z'
      fieldsType: FieldsV1
      fieldsV1:
        f:status:
          f:conditions:
            k:{"type":"ContainersReady"}:
              .: {}
              f:lastProbeTime: {}
              f:lastTransitionTime: {}
              f:observedGeneration: {}
              f:reason: {}
              f:status: {}
              f:type: {}
            k:{"type":"Initialized"}:
              .: {}
              f:lastProbeTime: {}
              f:lastTransitionTime: {}
              f:observedGeneration: {}
              f:status: {}
              f:type: {}
            k:{"type":"PodReadyToStartContainers"}:
              .: {}
              f:lastProbeTime: {}
              f:lastTransitionTime: {}
              f:observedGeneration: {}
              f:status: {}
              f:type: {}
            k:{"type":"PodScheduled"}:
              f:observedGeneration: {}
            k:{"type":"Ready"}:
              .: {}
              f:lastProbeTime: {}
              f:lastTransitionTime: {}
              f:observedGeneration: {}
              f:reason: {}
              f:status: {}
              f:type: {}
          f:containerStatuses: {}
          f:hostIP: {}
          f:hostIPs: {}
          f:initContainerStatuses: {}
          f:observedGeneration: {}
          f:phase: {}
          f:podIP: {}
          f:podIPs:
            .: {}
            k:{"ip":"100.96.43.66"}:
              .: {}
              f:ip: {}
          f:startTime: {}
      subresource: status
spec:
  volumes:
    - name: kube-api-access-4z2nr
      projected:
        sources:
          - serviceAccountToken:
              expirationSeconds: 3607
              path: token
          - configMap:
              name: kube-root-ca.crt
              items:
                - key: ca.crt
                  path: ca.crt
          - downwardAPI:
              items:
                - path: namespace
                  fieldRef:
                    apiVersion: v1
                    fieldPath: metadata.namespace
        defaultMode: 420
    - name: azure-keyvault-env
      emptyDir:
        medium: Memory
    - name: akv2k8s-client-cert
      secret:
        secretName: akv2k8s-auth0-extract-automation-cronjob
        defaultMode: 420
  initContainers:
    - name: copy-azurekeyvault-env
      image: twrcicdregister.azurecr.io/spvest/azure-keyvault-env:1.6.0
      command:
        - sh
        - '-c'
        - cp /usr/local/bin/azure-keyvault-env /azure-keyvault/
      resources: {}
      volumeMounts:
        - name: azure-keyvault-env
          mountPath: /azure-keyvault/
        - name: kube-api-access-4z2nr
          readOnly: true
          mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      terminationMessagePath: /dev/termination-log
      terminationMessagePolicy: File
      imagePullPolicy: IfNotPresent
      securityContext:
        capabilities:
          drop:
            - ALL
        privileged: true
        runAsNonRoot: false
        readOnlyRootFilesystem: false
  containers:
    - name: auth0-extract-automation-cronjob
      image: >-
        twrcicdregister.azurecr.io/tower.automation.auth0extracttosnowflake.job:1785457732
      command:
        - /azure-keyvault/azure-keyvault-env
      args:
        - dotnet
        - Tower.Automation.Auth0ExtractToSnowflake.dll
      env:
        - name: akv-secrets
          value: akvsecrets@azurekeyvault
        - name: ENV_INJECTOR_ARGS_SIGNATURE
          value: >-
            b1hwdlZ6ZStSazFyY3pHSkJxanV5bUNJOGNLaStRY2dSNDFSK3FwaXZPQXQ5MXl4emJYcW1rU0tHa0Zoc0dNRTMxUWdkeTJaNGFOdDA2YlYwam43dnRHL2dGdnczemhOejZlQjNXaHVQZ0dxSVNPU1RUUitiZzJraDh2aFJybG11MnFneUhxdDRtMW5MQTNRNFoxdEhRN0tnUFdXeTRWaytFaHFtMXlENkJtZTBoLy8rR1NCWHNMd2pzak8vTGhZM0E4OC8ySDF2dURUYXZvTDN6SktwUFpMWWlwcjZLa3RyeFRrQVpSeWVubnJYbGJxT2h5UC9UaU42VEFZQUZlVGpwUFNQaEpuNU5WSExQQ2haTXg4cHU3S1dhU3owQlkwSHBad3Z4T2JTeVo5eVU1NlQzVFJWSTBYZlpSTVB5b1cvd1lCNlArQnpkcEFuOGFOMGxIZEJ3PT0=
        - name: ENV_INJECTOR_ARGS_KEY
          value: >-
            LS0tLS1CRUdJTiBSU0EgUFVCTElDIEtFWS0tLS0tCk1JSUJJakFOQmdrcWhraUc5dzBCQVFFRkFBT0NBUThBTUlJQkNnS0NBUUVBM2ZjQk5SRkdCQisvbzc1L1ZaMTAKYlZJNVJBVzhPalpXdFdWb3RnTWZGNUdTS2VQSC8xYk11K2o4RmhKUEcwSlowNUZrL090NENpd2c4eDJzVVNjNgpic2tLdlV2bTFsWlNWNjRRb25YZXNmbmlDYitLRjdCbDdWajN4dno5STlwTzd1ek91NjFNRXZjQkptbHRNVzJaCnVwakJBV0hUUXZUSWJnWXYwZ0p1anFpNUtEcEZNSEprNXUxQmZqUUpRaXg0cmVocDc1dkJPWmwyQUc1eWRPaHcKam5MQm15VUNRc0RWTkYraFIvOU5pOW8vY0tNamRpaFM3ZlZjYkFSejlNZzduaUtKT2ZPY0x6Rml4Ujcxc0UwbQpMUGptNkpSY2p0YTVDSmFhSUxGNEgxaHh6cEhveFlVcEVEdHd3WFo3WG1HWGRQeFZEa0NBckRkd0szR0RXUnptCnh3SURBUUFCCi0tLS0tRU5EIFJTQSBQVUJMSUMgS0VZLS0tLS0K
        - name: ENV_INJECTOR_USE_AUTH_SERVICE
          value: 'true'
        - name: ENV_INJECTOR_POD_NAMESPACE
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
        - name: ENV_INJECTOR_POD_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.name
        - name: ENV_INJECTOR_CLIENT_CERT_DIR
          value: /var/client-cert/
        - name: ENV_INJECTOR_AUTH_SERVICE
          value: >-
            https://azure-key-vault-controller-akv2k8s-envinjector.akv2k8s.svc:9443
        - name: ENV_INJECTOR_AUTH_SERVICE_VALIDATION
          value: http://azure-key-vault-controller-akv2k8s-envinjector.akv2k8s.svc:80
        - name: ENV_INJECTOR_AUTH_SERVICE_SECRET
          value: akv2k8s-auth0-extract-automation-cronjob
      resources: {}
      volumeMounts:
        - name: kube-api-access-4z2nr
          readOnly: true
          mountPath: /var/run/secrets/kubernetes.io/serviceaccount
        - name: azure-keyvault-env
          readOnly: true
          mountPath: /azure-keyvault/
        - name: akv2k8s-client-cert
          readOnly: true
          mountPath: /var/client-cert/
      terminationMessagePath: /dev/termination-log
      terminationMessagePolicy: File
      imagePullPolicy: IfNotPresent
  restartPolicy: Never
  terminationGracePeriodSeconds: 30
  dnsPolicy: ClusterFirst
  serviceAccountName: default
  serviceAccount: default
  nodeName: aks-apps2-18298978-vmss0000e3
  securityContext: {}
  imagePullSecrets:
    - name: registrykey
  schedulerName: default-scheduler
  tolerations:
    - key: node.kubernetes.io/not-ready
      operator: Exists
      effect: NoExecute
      tolerationSeconds: 300
    - key: node.kubernetes.io/unreachable
      operator: Exists
      effect: NoExecute
      tolerationSeconds: 300
  priority: 0
  enableServiceLinks: true
  preemptionPolicy: PreemptLowerPriority
status:
  observedGeneration: 1
  phase: Failed
  conditions:
    - type: PodReadyToStartContainers
      observedGeneration: 1
      status: 'False'
      lastProbeTime: null
      lastTransitionTime: '2026-07-31T00:53:25Z'
    - type: Initialized
      observedGeneration: 1
      status: 'True'
      lastProbeTime: null
      lastTransitionTime: '2026-07-31T00:53:23Z'
    - type: Ready
      observedGeneration: 1
      status: 'False'
      lastProbeTime: null
      lastTransitionTime: '2026-07-31T00:53:21Z'
      reason: PodFailed
    - type: ContainersReady
      observedGeneration: 1
      status: 'False'
      lastProbeTime: null
      lastTransitionTime: '2026-07-31T00:53:21Z'
      reason: PodFailed
    - type: PodScheduled
      observedGeneration: 1
      status: 'True'
      lastProbeTime: null
      lastTransitionTime: '2026-07-31T00:53:21Z'
  hostIP: 10.148.159.147
  hostIPs:
    - ip: 10.148.159.147
  podIP: 100.96.43.66
  podIPs:
    - ip: 100.96.43.66
  startTime: '2026-07-31T00:53:21Z'
  initContainerStatuses:
    - name: copy-azurekeyvault-env
      state:
        terminated:
          exitCode: 0
          reason: Completed
          startedAt: '2026-07-31T00:53:21Z'
          finishedAt: '2026-07-31T00:53:22Z'
          containerID: >-
            containerd://d861a11c970f778a4d4fd60c2ee08d00f49c5b8c50038e2a39465c0b28baf0a2
      lastState: {}
      ready: true
      restartCount: 0
      image: twrcicdregister.azurecr.io/spvest/azure-keyvault-env:1.6.0
      imageID: >-
        twrcicdregister.azurecr.io/spvest/azure-keyvault-env@sha256:b4a43be975feb5456ea33e09691b9e9617098cf2ca9f8a60ebe6cdecb433aa34
      containerID: >-
        containerd://d861a11c970f778a4d4fd60c2ee08d00f49c5b8c50038e2a39465c0b28baf0a2
      started: false
      resources: {}
      volumeMounts:
        - name: azure-keyvault-env
          mountPath: /azure-keyvault/
        - name: kube-api-access-4z2nr
          mountPath: /var/run/secrets/kubernetes.io/serviceaccount
          readOnly: true
          recursiveReadOnly: Disabled
  containerStatuses:
    - name: auth0-extract-automation-cronjob
      state:
        terminated:
          exitCode: 139
          reason: Error
          startedAt: '2026-07-31T00:53:23Z'
          finishedAt: '2026-07-31T00:53:23Z'
          containerID: >-
            containerd://3d6105cbd521dd6e78c7d4770531597a7fd83cfcf8d789cf08f5934754ab9cfe
      lastState: {}
      ready: false
      restartCount: 0
      image: >-
        twrcicdregister.azurecr.io/tower.automation.auth0extracttosnowflake.job:1785457732
      imageID: >-
        twrcicdregister.azurecr.io/tower.automation.auth0extracttosnowflake.job@sha256:2a798fce38406ec5f6501b77bf991974b40718692c277739e50a4d96f2646839
      containerID: >-
        containerd://3d6105cbd521dd6e78c7d4770531597a7fd83cfcf8d789cf08f5934754ab9cfe
      started: false
      resources: {}
      volumeMounts:
        - name: kube-api-access-4z2nr
          mountPath: /var/run/secrets/kubernetes.io/serviceaccount
          readOnly: true
          recursiveReadOnly: Disabled
        - name: azure-keyvault-env
          mountPath: /azure-keyvault/
          readOnly: true
          recursiveReadOnly: Disabled
        - name: akv2k8s-client-cert
          mountPath: /var/client-cert/
          readOnly: true
          recursiveReadOnly: Disabled
  qosClass: BestEffort
